

//kaishiqignqiu
export let STATR_FETCH_MAIN_PAGE_DATA="STATR_FETCH_MAIN_PAGE_DATA";
export let FETCH_MAIN_PAGE_DATA="FETCH_MAIN_PAGE_DATA";

//kaishiqignqiu
export let STATR_FETCH_GIRL_PAGE_DATA="STATR_FETCH_GIRL_PAGE_DATA";
export let FETCH_GIRL_PAGE_DATA="FETCH_GIRL_PAGE_DATA";
